Description = "为了更好的开源世界~"
Keywords =  "史莱姆诺尔, 萌诺尔, 诺尔, 博客, 程序员, 自学, 编程, 笔记, 技术, 分享, .NET, C#"
Subtitle = "前进! 前进! 不择手段的前进!"
AuthorImg = "/img/avatar.jpg"
AuthorName = "史莱姆诺尔"
Introduce = "我很可爱, 请给我糖 o(*////▽////*)q"
DateFormat = "2006-01-02"
YearFormat = "2006年"
MonthFormat = "01-02"

ArticleDecContent = "本博客文章除特别声明外，均采用 <a href='https://creativecommons.org/licenses/by-nc-sa/3.0/' target='_blank' style='text-decoration: underline;'>CC BY-NC-SA 3.0</a>许可协议，转载请注明出处！"

[Footer]
  StorageLink = "https://www.ucloud.cn/"
  StorageName = "UCloud云存储"
  ICPLink = "http://beian.miit.gov.cn"
  ICPNo = "粤ICP备18047355号"

[[Socials]]
  Name = "GitHub"
  Icon = "github"
  URL = "https://github.com/slimenull/"

[[Socials]]
  Name = "Bilibili"
  Icon = "tv"
  URL = "https://space.bilibili.com/441842015"

[[Links]]
  Name = "Vertillusion"
  Permalink = "https://vertillusion.xyz/"