Description = "For the better opensource world."
Keywords =  "SlimeNull, Blog, Programmer, Learning, Programming, Technology, Share, .NET, C#"
Subtitle = "March forward ! March forward! March forward by all means necessary!"
AuthorImg = "/img/avatar.jpg"
AuthorName = "SlimeNull"
Introduce = "I'm cute, candy please o(*////▽////*)q"
DateFormat = "2006/01/02"
YearFormat = "2006Y"
MonthFormat = "01/02"

ArticleDecContent = "This blog post article is under the <a href='https://creativecommons.org/licenses/by-nc-sa/3.0/' target='_blank' style='text-decoration: underline;'>CC BY-NC-SA 3.0</a> license,Please indicate the source!"

[Footer]
  StorageLink = "https://www.ucloud.cn/"
  StorageName = "UCloud Storage"
  ICPLink = "http://beian.miit.gov.cn"
  ICPNo = "ICP.NO 2021017656"

[[Socials]]
  Name = "GitHub"
  Icon = "github"
  URL = "https://github.com/elkan1788/"

[[Socials]]
  Name = "ZhiHu"
  Icon = "globe"
  URL = "https://www.zhihu.com/people/fan-meng-xing-chen-1"

[[Links]]
  Name = "Vertillusion"
  Permalink = "https://vertillusion.xyz/"